# Path to the input CSV (absolute or relative)

#input_file: "./data/input.csv"
input_file: "./data/Take_2025-07-24 04.13.33 PM.csv"



# Time interval in seconds. Use null for end to cover entire file.
interval:
  start_time: 0
  end_time: null

# Extra time markers in seconds to draw on plots
# Use null for no markers
time_markers:
  null
#  [10, 200]

# List of IDs (rigid-body base names) to analyze; empty = all
groups: [H1]

# Kinematics (smoothing) options
# savgol / window

kinematics:
  smoothing: false
  smoothing_window: 10
  smoothing_polyorder: 2
  smoothing_method: window

# Filtering thresholds for speed values. Either speed of angular speed
filtering:
  enable: false

  speed_lower: null
  speed_upper: null
  angular_speed_lower: 0.001
  angular_speed_upper: 50

  x_lower: null
  x_upper: null
  y_lower: null
  y_upper: null
  z_lower: null
  z_upper: null

# Output settings
output:
  plot_trajectory_2d: true
  plot_trajectory_3d: true
  plot_linear_speed: true
  plot_angular_speed: true

  # Plot customization
  full_size_plots: true
  x_limit: null
  y_limit: null

  export_speed_stats: true
  export_angular_stats: true

  export_speed: true

  export_filtered: true
  export_marker_list: true
  export_angular_speed: true
  output_dir: "./results"

# Preprocess settings
preprocess:
  enable: true
  output_file: "./results/trimmed.csv"
  summary_file: "./results/summary.txt"

# Settings for the interactive web application
webapp:
  port: 3010

# Settings for filter comparison utility
filter_test:
  enable: true
  # optional: specify which rigid body to use; defaults to the first one
  group: H1
  # choose data source: angular_speed, position_x, position_y or position_z
  source: angular_speed
  # time range for the test
  start_time: 55
  end_time: 65


  filters:
    - type: moving_average
      window: 5
    - type: ema
      alpha: 0.2
    - type: butterworth
      order: 2
      cutoff: 2.0
    - type: savgol
      window: 7
      polyorder: 2
    - type: fir
      numtaps: 21
      cutoff: 2.0
    - type: window
      window: 10
    - type: decimal_removal
      digits: 2
    - type: lateral_inhibition
      tau_fast: 5
      tau_slow: 30
      k_inhibit: 1.0
