# Path to the input CSV (absolute or relative)

# input_file: "./data/m07_0902.csv"
input_file: "/Volumes/SenzaiLab/Kai/#Recording/m07/250911/250911.csv"


# Preprocess settings
preprocess:
  enable: true
  # optional: also copy the trimmed CSV
  output_file: null
  # optional: also copy the summary file
  summary_file: null

# Time interval in seconds. Use null for end to cover entire file.
interval:
  start_time: 0
  end_time: null

# Extra time markers in seconds to draw on plots
# Use null for no markers
time_markers:
  null
#  [10, 200]

# List of IDs (rigid-body base names) to analyze; empty = all
groups: [H1]

# Kinematics (smoothing) options
# Available methods: savgol / ema / window / lateral_inhibition

kinematics:
  smoothing: false
  smoothing_window: 10
  smoothing_polyorder: 2
  smoothing_method: window

# Filtering thresholds for speed values. Either speed of angular speed
filtering:
  enable: true

  speed_lower: 2000
  speed_upper: null
  angular_speed_lower: null
  angular_speed_upper: null

  x_lower: null
  x_upper: null
  y_lower: null
  y_upper: null
  z_lower: null
  z_upper: null

no_moving:
  enable: true
  # remove stretches where speed stays zero for at least this many frames
  window: 10
  # additionally drop this many frames after each no-movement period
  after: 10

# Output settings
output:
  plot_trajectory_2d: true
  plot_trajectory_3d: false
  plot_linear_speed: true
  plot_angular_speed: true

  # Plot customization
  full_size_plots: true
  x_limit: null
  y_limit: null

  export_speed_stats: false
  export_angular_stats: false

  export_speed: false

  export_filtered: false
  export_marker_list: false
  export_angular_speed: false

  export_metrics:
    enable: false
    metrics: [ trajectory, speed, angular_speed ]
    format: csv

  export_head_direction: true
  head_direction:
    include_frames: true
    format: degrees  # degrees or quaternion
  output_dir: "./results"

# Logging configuration
logging:
  level: info
  file: run.log

# Settings for the interactive web application
webapp:
  port: 3010

# Settings for filter comparison utility
#filter_test:
#  enable: false
#  # optional: specify which rigid body to use; defaults to the first one
#  group: H1
#  # choose data source: angular_speed, position_x, position_y or position_z
#  source: angular_speed
#  # time range for the test
#  start_time: 55
#  end_time: 65
#
#
#  filters:
#    - type: moving_average
#      window: 5
#    - type: ema
#      alpha: 0.2
#    - type: butterworth
#      order: 2
#      cutoff: 2.0
#    - type: savgol
#      window: 7
#      polyorder: 2
#    - type: window
#      window: 10
#    - type: lateral_inhibition
#      tau_fast: 5
#      tau_slow: 30
#      k_inhibit: 1.0
