# Path to the input CSV (absolute or relative)
input_file: "./data/output.csv"

# Frame interval (inclusive). Use null for end to cover entire file.
interval:
  start_frame: 0
  end_frame: null

# Extra frame “time markers” (integers) to draw on plots
# Use null for no markers
time_markers: null

# List of IDs (rigid-body base names) to analyze; empty = all
groups: [H1]

# Kinematics (smoothing) options
kinematics:
  smoothing: false
  smoothing_window: 5
  smoothing_polyorder: 2
  smoothing_method: savgol

# Output settings
output:
  plots: true
  export_filtered: false
  export_marker_list: false
  output_dir: "./results"