# Path to the input CSV (absolute or relative)
#input_file: "./data/output1.csv"
input_file: "./data/input.csv"


# Time interval in seconds. Use null for end to cover entire file.
interval:
  start_time: 0
  end_time: null

# Extra frame “time markers” (integers) to draw on plots
# Use null for no markers
time_markers: null

# List of IDs (rigid-body base names) to analyze; empty = all
groups: [H1]

# Kinematics (smoothing) options
kinematics:
  smoothing: false
  smoothing_window: 5
  smoothing_polyorder: 2
  smoothing_method: savgol

# Filtering thresholds for speed values. Either speed of angular speed
filtering:
  enable: true
  speed_lower: 0.01
  speed_upper: 3000
  angular_speed_lower: null
  angular_speed_upper: null

# Output settings
output:
  plot_trajectory_2d: true
  plot_trajectory_3d: false
  plot_linear_speed: true
  plot_angular_speed: true

  # Plot customization
  full_size_plots: false
  x_limit: null
  y_limit: null

  export_speed_stats: false
  export_angular_stats: false

  export_speed: false

  export_filtered: false
  export_marker_list: false
  export_angular_speed: false
  output_dir: "./results"

# Preprocess settings
preprocess:
  enable: true
  output_file: "./data/output.csv"
  summary_file: "./data/summary.txt"
