# Path to the input CSV (absolute or relative)
input_file: "./data/output.csv"

# Frame interval (inclusive). Use null for end to cover entire file.
interval:
  start_frame: 0
  end_frame: null

# Extra frame “time markers” (integers) to draw on plots
# Use null for no markers
time_markers: null

# List of IDs (rigid-body base names) to analyze; empty = all
groups: [H1]

# Kinematics (smoothing) options
kinematics:
  smoothing: false
  smoothing_window: 5
  smoothing_polyorder: 2
  smoothing_method: savgol

# Filtering thresholds for speed values
filtering:
  enable: false
  speed_lower: null
  speed_upper: null
  angular_speed_lower: null
  angular_speed_upper: null

# Output settings
output:
  plot_trajectory_2d: true
  plot_trajectory_3d: true
  plot_linear_speed: false
  plot_angular_speed: true

  export_speed: false

  export_filtered: false
  export_marker_list: false
  export_angular_speed: false
  output_dir: "./results"
